apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-fover-library
spec:
  replicas: 3
  template:
    metadata:
      name: pod-fover-library
      labels:
        app: pod-fover-library
    spec:
      containers:
        - name: container-fover-library
          image: fover-library
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: pod-fover-library
---
apiVersion: v1
kind: Service
metadata:
  name: svc-fover-library
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
  selector:
    app: pod-fover-library