apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-accounts-portal
spec:
  replicas: 3
  template:
    metadata:
      name: pod-accounts-portal
      labels:
        app: pod-accounts-portal
    spec:
      containers:
        - name: container-accounts-portal
          image: accounts-portal
          imagePullPolicy: Never
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: pod-accounts-portal
---
apiVersion: v1
kind: Service
metadata:
  name: svc-accounts-portal
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
  selector:
    app: pod-accounts-portal