name: Deploy app DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t registry.digitalocean.com/foverbr/fover-library:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        
      - name: Login docker
        run: doctl registry login --expiry-seconds 600

      - name: Push image
        run: docker push registry.digitalocean.com/foverbr/fover-library:$(echo $GITHUB_SHA | head -c7)